// flow-typed signature: 1974bd9109133b5792b3316527bea17e
// flow-typed version: <<STUB>>/normalize.css_v^8.0.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
